### ISSUE TITLE
AssertionError: size of input tensor and input format are different. 

### ISSUE THREAD

**Issue by dengqingkang** [zswang666/Stereo-LiDAR-CCVNorm#3]
lib/python3.5/site-packages/tensorboardX/utils.py", line 103, in convert_to_HWC
AssertionError: size of input tensor and input format are different.         
tensor shape: (1, 3, 256, 512), input_format: CHW
请问您遇到过这个问题嘛，是怎么样解决的

**Comment by dengqingkang** [comment]
我是直接对input_format: CHW重新取值为NCHW，会对结果有影响嘛

**Comment by zyl1336110861** [comment]
I encountered with this problem. So could you tell me how did you solve this problem? Thank you very much!

**Comment by zyl1336110861** [comment]
@dengqingkang I encountered with this problem. So could you tell me how did you solve this problem? Thank you very much!

**Comment by zyl1336110861** [comment]
Solved. Just replace the add_image with the add_images. Sorry to bother you.
